#!/bin/sh

# Monitor:
bspc monitor -d 1 2 3 4 5

# Window:
bspc config border_width 0

# Binary space layout configs:
bspc config window_gap 5
bspc config split_ratio 0.52

# Monocle layout configs:
bspc config borderless_monocle true
bspc config gapless_monocle true

# Window rules:
# bspc rule -a <CLASS>
#     desktop=<DESKTOP_NUMBER>
#     state=<WINDOW_STATE>
#     follow=on/off
#     manage=on/off

bspc rule -a obsidian           desktop='^1'
bspc rule -a libreoffice        desktop='^1'
bspc rule -a GParted            desktop='^1'
bspc rule -a transmission-gtk   desktop='^1'
bspc rule -a Brave-browser      desktop='^2'
bspc rule -a kitty              desktop='^3'
bspc rule -a Thunar             desktop='^4'
bspc rule -a File_manager       desktop='^4'
bspc rule -a loupe              desktop='^4'
bspc rule -a vlc                desktop='^5'

bspc rule -a Blueman-manager        state=floating
bspc rule -a pavucontrol            state=floating
bspc rule -a nm-connection-editor   state=floating
bspc rule -a Lxappearance           state=floating
bspc rule -a kdeconnect.app         state=floating

# Keymap daemon:
pgrep -x sxhkd > /dev/null || sxhkd &

# Panel:
bash ~/.config/polybar/launch.sh &
