#! /bin/sh

# Auto start scripts:
bash ~/.config/autostart/autostart.sh

bspc monitor -d \
  Primary \
  Browser \
  Terminal \
  Files

bspc config border_width            0

# Binary space layout configs:
bspc config window_gap              5
bspc config split_ratio          0.52

# Monocle layout configs:
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules:
# bspc rule -a <CLASS>
#     desktop=<DESKTOP_NUMBER>
#     state=<WINDOW_STATE>
#     follow=on/off
#     manage=on/off

bspc rule -a Google-chrome desktop='^2'
bspc rule -a kitty desktop='^3' state=fullscreen
bspc rule -a Alacritty desktop='^3' state=fullscreen
bspc rule -a Thunar desktop='^4'

bspc rule -a Blueman-manager state=floating
bspc rule -a Pavucontrol state=floating
