font_family     Fira Code Retina
font_size       11.5

adjust_line_height 1

#font_family     JetBrains Mono
#font_size       11.5

#font_family     Ubuntu Mono
#font_size       14

#font_family     Menlo
#font_size       13

#include ./solarized.conf
