font_family     Fira Mono
#font_family     Fira Code
#font_family     Droid Sans Mono 
#font_family     JetBrains Mono
#font_family     Menlo
#font_family     SF Mono Medium

#font_size 11.5
#font_size 10.5
#font_size 10.6
#font_size 10.7
#font_size 12

adjust_line_height  2
#include ./Atom.conf

