#font_family         Fira Code Retina
#bold_font           Fira Code Bold
#font_size           11.5

#font_family					Operator Mono SSM Lig Book
#italic_font					Operator Mono SSM Lig Book Italic
#bold_font						Operator Mono SSM Lig Bold
#bold_italic_font	  Operator Mono SSM	Lig Bold Italic
#disable_ligatures   always
#adjust_line_height	1

#font_family         Ubuntu Mono
#font_size           13.5

font_family					JetBrains Mono
font_size						11.5
#adjust_line_height	3
