# background_opacity        0.8
# background_blur           1
text_composition_strategy legacy

# disable_ligatures         always
undercurl_style           thin-dense
adjust_line_height        0

# Font:
font_size                 11.7
font_family               Rec Mono SemiCasual
bold_font                 Rec Mono SemiCasual Bold
italic_font               Rec Mono SemiCasual Italic
bold_italic_font          Rec Mono SemiCasual Bold Italic

# Color scheme:
include ~/.config/kitty/themes/index.conf
