[bar/main]

;; Monitor:
monitor =
monitor-fallback =
monitor-strict = false
monitor-exact = true

;; Position:
bottom = false
fixed-center = true

;; Window manager:
override-redirect = false
wm-restack = bspwm

;; Size:
width = 99.3%
height = 32

;; Margin:
offset-x = 5
offset-y = 5

;; Padding:
padding-left = 1
padding-right = 2

;; Border:
radius = 5

;; Color:
background = ${color.background}
foreground = ${color.foreground}

;; Fonts:
font-0 = Roboto:style=Regular:size=11;3
font-1 = Feather:style=Medium:size=13;4
font-2 = Noto Sans=Regular:size=11;3

;; Modules:
modules-left = workspaces
modules-center = title
modules-right = tray volume date

enable-ipc = true
