set-option -g mouse on
set -g set-clipboard on
set -g history-limit 10000
# set -g default-terminal "xterm-256color"

set-option -g default-terminal "xterm-256color"
set-option -g terminal-overrides "xterm-256color"

## Alacritty
#set  -g default-terminal "tmux-256color"
#set -ag terminal-overrides ",alacritty:RGB"

## Gnome Terminal
#set -g default-terminal "tmux-256color"
#set -ag terminal-overrides ",xterm-256color:RGB"

#set -g default-terminal 'screen-256color'
# set -ga terminal-overrides ',*256col*:Tc'

set-window-option -g xterm-keys on
set -g escape-time 10
set-option -g repeat-time 0
set -g monitor-activity on
set -g visual-activity on
set -g focus-events on
set -g status-interval 1
set -g status
# source /usr/share/powerline/bindings/tmux/powerline.conf

