set-option -g mouse on
set -g set-clipboard on
set -g history-limit 10000
#set -g default-terminal "xterm"
set-option -g default-terminal "xterm-256color"
set-option -g terminal-overrides "xterm-256color"
set-window-option -g xterm-keys on
set -g escape-time 10
set-option -g repeat-time 0
set -g monitor-activity on
set -g visual-activity on
set -g focus-events on
set -g status-interval 1
