return {
    error = "",
    warning = "",
    circle = "",
    info = "",

    lsp_kinds = {
        Text = "",
        Variable = "",
        Constant = "",
        Value = "",
        Function = "",
        Enum = "",
        EnumMember = "",
        Class = "",
        Constructor = "",
        Field = "",
        Method = "",
        Interface = "",
        Struct = "",
        TypeParameter = "",
        Property = "",
        Unit = "",
        Keyword = "",
        Snippet = "",
        Color = "",
        Reference = "",
        Module = "",
        File = "",
        Folder = "",
        Event = "",
        Operator = "",
    },
}
