; TODO: See if there's an update of #1752

[module/battery]
type = internal/battery

full-at = 99
low-at = 9

battery = BAT0
adapter = AC

; format-full = "<label-full>  "
; format-low = "<label-low>  "
; format-charging = "<ramp-capacity>  "
; format-discharging = "<ramp-capacity>  "

; label-full = 
; label-low = 

; ramp-capacity-0 = 
; ramp-capacity-1 = 
; ramp-capacity-2 = 
; ramp-capacity-4 = 

; label-full = 󰁹 %percentage%%
; label-low = 󱃍 %percentage%%
label-full = 󰁹
label-low = 󱃍
label-charging = %percentage%%
label-discharging = %percentage%%

format-full = "<label-full>"
format-low = "<label-low>"
format-charging = "<animation-charging>"
format-discharging = "<ramp-capacity> "

ramp-capacity-0 = 󰂎
ramp-capacity-1 = 󰁺
ramp-capacity-2 = 󰁻
ramp-capacity-3 = 󰁼
ramp-capacity-4 = 󰁽
ramp-capacity-5 = 󰁾
ramp-capacity-6 = 󰁿
ramp-capacity-7 = 󰂀
ramp-capacity-8 = 󰂁
ramp-capacity-9 = 󰂂

animation-charging-0  = 󰢟
animation-charging-1  = 󰢜
animation-charging-2  = 󰂆
animation-charging-3  = 󰂇
animation-charging-4  = 󰂈
animation-charging-5  = 󰢝
animation-charging-6  = 󰂉
animation-charging-7  = 󰢞
animation-charging-8  = 󰂊
animation-charging-9  = 󰂋
animation-charging-10 = 󰂅

animation-charging-framerate = 500
