#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
pkill -9 ibus-daemon flameshot redshift nitrogen polybar picom &
flameshot &
picom &
redshift -l 23.707310:90.415482 -m randr -t 4250:3250 &
# python $HOME/.config/pygen/nitrogen.py &
nitrogen --restore &
$HOME/.config/polybar/launch.sh


bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config external_rules_command ~/.config/bspwm/rules

## Mouse Bindings
# Set mouse 1 to move floating windows
bspc config pointer_action1 move

# Mouse 2 button resizes the window by side
bspc config pointer_action2 resize_side

# Mouse 3 button (right mouse) resize by corner
bspc config pointer_action2 resize_corner

## Desktop rules & Window States rules
bspc rule -a vlc desktop='^1' follow=on
bspc rule -a kitty desktop='^2' #state=fullscreen
bspc rule -a Google-chrome desktop='^3' follow=on
bspc rule -a discord desktop='^7' follow=on state=tiling
bspc rule -a qutebrowser desktop='^3' follow=on
#bspc rule -a Code desktop='^3' follow=on state=tiling
bspc rule -a Thunar desktop='^5' follow=on
bspc rule -a Lxappearance desktop='^9'state=floating focus=on
bspc rule -a Nitrogen desktop='^9' state=floating focus=on
bspc rule -a Pavucontrol desktop='^9'state=floating focus=on center=on


######### BSPWM DEFAULTS (USELESS THINGS) ############
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
