#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#picom -f &
redshift -l 23.707310:90.415482 -m randr -t 4500:3500 &
#python $HOME/.config/pygen/pygen.py &
nitrogen --restore &
$HOME/.config/polybar/launch.sh
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chrome desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
