[window]
padding.x = 3
padding.y = 2

[env]
TERM = "alacritty"

[font]
# size = 11.7
size = 10
offset.y = 1

[font.normal]
family = "Rec Mono SemiCasual"
style = "Regular"

[font.bold]
family = "Rec Mono SemiCasual"
style = "Bold"

[font.italic]
family = "Rec Mono SemiCasual"
style = "Italic"

[font.bold_italic]
family = "Rec Mono SemiCasual"
style = "Bold Italic"

# Gruvbox dark (hard variant)
# Primary colors
[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

# Normal colors
[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

# Bright colors
[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"
